apiVersion: v1
kind: Pod
metadata:
  name: app-user
  labels:
    app: app-user-label
    language: python

spec:
  containers:
    - name: app-user-container
      image: zyndev/app-user:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 20000
  restartPolicy: Always
  