:toc:

== Docker Network

Docker 网络是 Docker 容器的一个重要概念。容器之间、容器与宿主机之间的网络通信都依赖于 Docker 网络。

Docker 网络的类型有很多，包括：

* **bridge 网络**：默认的网络模式，类似虚拟机的 NAT 模式。
* **host 网络**：容器与宿主机之间的网络无隔离，即容器直接使用宿主机网络。
* **none 网络**：容器禁用所有网络。
* **overlay 网络**：利用 VxLAN 实现的 bridge 模式，具有跨主机通信的能力。

**bridge 网络**

bridge 网络是 Docker 中最常用的网络模式。在 bridge 网络中，Docker 在宿主机上创建一个虚拟网桥，容器连接到这个虚拟网桥上。容器之间可以通过虚拟网桥进行通信，也可以通过虚拟网桥与宿主机进行通信。

**host 网络**

host 网络是 bridge 网络的一种特殊模式。在 host 网络中，容器直接使用宿主机的网络，包括 IP 地址、子网掩码、网关等。容器之间可以通过宿主机网络进行通信，也可以通过宿主机网络与宿主机进行通信。

**none 网络**

none 网络是 bridge 网络的一种特殊模式。在 none 网络中，容器禁用所有网络。容器之间不能进行通信，也不能与宿主机进行通信。

**overlay 网络**

overlay 网络是 Docker 提供的一种跨主机网络。在 overlay 网络中，Docker 使用 VxLAN 技术在多个主机之间创建一个逻辑网络。容器可以连接到这个逻辑网络上，实现跨主机通信。


=== Docker 网络教程

**Docker 网络基本操作**

* 查看 Docker 网络：`docker network ls`
* 创建 Docker 网络：`docker network create <network-name>`
* 删除 Docker 网络：`docker network rm <network-name>`
* 连接容器到网络：`docker run --network <network-name> <container-name>`
* 从网络中删除容器：`docker network disconnect <network-name> <container-name>`

**Docker 网络通信**

容器之间可以通过 IP 地址或端口进行通信。

* 容器 IP 地址：容器启动时会分配一个 IP 地址，这个 IP 地址是容器在 Docker 网络中的唯一标识。
* 端口映射：可以通过端口映射将容器的端口映射到宿主机的端口，这样就可以通过宿主机的端口访问容器。

**Docker 网络的应用**

Docker 网络可以用于以下应用：

* 容器之间的通信
* 容器与宿主机的通信
* 跨主机容器的通信
* 微服务的部署

**Docker 网络的最佳实践**

* 使用 bridge 网络作为默认网络模式。
* 使用 overlay 网络实现跨主机容器通信。
* 使用端口映射将容器的端口映射到宿主机的端口，方便访问容器。

**Docker 网络的常见问题**

* 容器之间无法通信：检查容器是否连接到同一个网络，检查容器是否有 IP 地址。
* 容器无法访问宿主机：检查容器是否连接到同一个网络，检查容器是否有 IP 地址，检查宿主机的防火墙设置。
* 容器无法访问互联网：检查容器是否连接到 bridge 网络，检查宿主机的网络设置。


[source,bash]
----
docker network ls
docker network inspect bridge
----

[source,bash]
----
docker run -dit --rm --name app1 alpine ash
docker run -dit --rm --name app1 alpine ash
----

[source,bash]
----
docker stop app1
docker stop app2
----


[source,bash]
----
docker network create my-net
docker run -dit --rm --network my-net --name app1 alpine ash
docker run -dit --rm --network my-net --name app2 alpine ash
docker network inspect my-net
----

自定义网络 + 别名

.环境1
[source,bash]
----
docker network create net-env1
docker run -dit --rm --network net-env1 --network-alias app1 --name env1-app1 alpine ash
docker run -dit --rm --network net-env1 --network-alias app2 --name env1-app2 alpine ash
docker network inspect net-env1
----

.环境2
[source,bash]
----
docker network create net-env2
docker run -dit --rm --network net-env2 --network-alias app1 --name env2-app1 alpine ash
docker run -dit --rm --network net-env2 --network-alias app2 --name env2-app2 alpine ash
docker network inspect net-env2
----

